FROM elasticsearch:5.1.1

MAINTAINER Boris Belozovsky <boriska70@gmail.com>

RUN /bin/echo https_proxy=$https_proxy > ~/.wgetrc

COPY elasticsearch-vagrant.yml /usr/share/elasticsearch/config/elasticsearch.yml

RUN /usr/bin/wget https://artifacts.elastic.co/downloads/packs/x-pack/x-pack-5.1.1.zip -O /tmp/x-pack-5.1.1.zip
RUN /usr/share/elasticsearch/bin/elasticsearch-plugin install --batch file:///tmp/x-pack-5.1.1.zip
